import assert from 'node:assert/strict';
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:8787';
if(!['127.0.0.1','localhost'].includes(new URL(base).hostname))throw Error('Integration tests only write to a local test server.');
const id=crypto.randomUUID(),token=[...crypto.getRandomValues(new Uint8Array(32))].map(v=>v.toString(16).padStart(2,'0')).join('');
const url=base+'/api/schools/'+id;
const data={name:'Integration test school',year:'2025-2026',sheets:{'1':{B15:'Test headmaster'}},completed:['1']};
const call=(method,body,auth=token,extra={})=>fetch(url,{method,headers:{Authorization:'Bearer '+auth,'Content-Type':'application/json',...extra},...(body?{body:JSON.stringify(body)}:{})});
assert.equal((await call('GET',null,'')).status,401);
let response=await call('PUT',{data,revision:0});assert.equal(response.status,201);assert.equal((await response.json()).revision,1);
response=await call('GET');assert.equal(response.status,200);assert.deepEqual((await response.json()).data,data);
assert.equal((await call('GET',null,'0'.repeat(64))).status,404);
assert.equal((await call('PUT',{data,revision:1},'0'.repeat(64))).status,404);
assert.equal((await call('PUT',{data,revision:0})).status,409);
assert.equal((await call('PUT',{data,revision:1},token,{Origin:'https://example.net'})).status,403);
assert.equal((await call('PUT',{data:{...data,sheets:{'1':{A12:'attempt to change heading'}}},revision:1})).status,400);
assert.equal((await call('PUT',{data,revision:1})).status,200);
const concurrent=await Promise.all([call('PUT',{data,revision:2}),call('PUT',{data,revision:2})]);
assert.deepEqual(concurrent.map(r=>r.status).sort(),[200,409]);
assert.equal((await call('PUT',{data:{...data,name:'x'.repeat(270000)},revision:3})).status,400);
console.log('PASS: cloud persistence, recovery authorization, wrong-token denial, cross-origin denial, validation, payload limits and concurrent-write protection.');
